apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gke-test-deployment
  name: gke-test-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-test-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gke-test-deployment
    spec:
      containers:
        - image: gcr.io/nordcloud2021/github.com/duchungluu/nordcloud-gcp
          imagePullPolicy: Always
          name: gke-test-image
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /db
              name: gke-test-storage
      volumes:
        - name: gke-test-storage
          persistentVolumeClaim:
            claimName: gke-test-storage-claim
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: gke-test-deployment
  name: gke-test-hpa
  namespace: default
spec:
  maxReplicas: 8
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gke-test-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: gke-loadbalance-expose-service
spec:
  type: LoadBalancer
  selector:
    app: gke-test-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---

