apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test-deployment
  namespace: default
  labels:
    app: gke-test-deployment
spec:
  replicas: 2 #number of pods
  selector:
    matchLabels:
      app: gke-test-deployment
  template:
    metadata:
      labels:
        app: gke-test-deployment
    spec:
      containers:
        - name: gke-test-image
          image: gcr.io/nordcloud2021/gke-test-image:v1.0.0
          #image: gcr.io/$PROJECT_ID/gke-test-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
          - name: gke-test-storage
            mountPath: /db
      volumes:
        - name: gke-test-storage
          persistentVolumeClaim: 
            claimName: gke-test-storage-claim
            